### ISSUE TITLE
Upgrade to Fluent Assertions 5

### ISSUE THREAD

**Issue by kevinkuszyk** [fluentassertions/fluentassertions.mvc#33]

**Comment by rikrak** [comment]
I had a quick attempt at upgrading the code to FluentAssertions v5, but it look slike FA5 no longer supports .NET 4.  This means the automatic NuGet upgrade fails as the MVC3 and MVC4 projects target .NET 4.  I wasn't sure how best to proceed.  
Can the MVC3 & 4 projects be simply upgraded to target .NET 4.5?

**Comment by kevinkuszyk** [comment]
@rikrak thanks for taking a look at this.

I just had a look in one of our projects here, and it looks like MVC 5 only supports `net45` and up, so yes feel free to go ahead an upgrade all the projects to that.

As this is going to be a breaking change, if you hit problems with the MVC 3  and 4 projects I wouldn't have a problem with dropping support for them now.

**Comment by rikrak** [comment]
Update:
I've upgraded the MVC3 & MVC4 projects to .NET 4.5 and upgraded FA to v5.0.0.  All the tests are passing :-)
I haven't, however tested any of this with a "real" project yet.
I've pushed my changes to my fork of this project on GitHub (branch: FA5_Upgrade).

I'm new to Git/GitHub, so I'm not sure what I need to do next... :-)

**Comment by kevinkuszyk** [comment]
Great, all looks good and you're on the right track so far.

Next up, can you open a pull request ([more info here](https://help.github.com/articles/creating-a-pull-request/))?  Once I've merged your changes in I'll ship a beta to nuget.

**Comment by rikrak** [comment]
OK, Pull request created.

**Comment by kevinkuszyk** [comment]
Fixed in #36.

**Comment by kevinkuszyk** [comment]
@rikrak any issues with the beta?  If not I'll try to get a full version out next week.

**Comment by rikrak** [comment]
It's all good here.  I've had it in our project for a week or so without issue.  
For Ref: We're using v5.1.2 of FluentAssertions.

**Comment by kevinkuszyk** [comment]
Thanks @rikrak.  I just pushed 0.7.0.  It should show up on nuget shortly.
