### ISSUE TITLE
Remove compiler directives and asp.net core code

### ISSUE THREAD

**Issue by kevinkuszyk** [fluentassertions/fluentassertions.mvc#38]
We've now moved the mvc core code out into another repro, but we still have the compiler directives and mvc code `using`s here.  These can all be removed now.

**Comment by rikrak** [comment]
I've added a PR for this.  Is it possible to link PRs with issues?

**Comment by rikrak** [comment]
Experimental link: #39

**Comment by kevinkuszyk** [comment]
Thanks for the PR - it's much appreciated!
